apps/base/urls.py
from django.urls import path, include

from .views import home_page, faoliyat, contactus


urlpatterns = [
    path("", home_page, name="home_page"),
    path("faoliyat/", faoliyat, name="faoliyat"),
    path("contactus/", contactus, name="contactus"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [ 
    path('admin/', admin.site.urls),
    path("", include("apps.base.urls")),
    path("gallery/", include("apps.gallery.urls")),
    path("library/", include("apps.library.urls")),
    path("news/", include("apps.news.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/base/models.py
from django.db import models

# Create your models here.

class Department(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    


class ContactUs(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=255)
    description = models.TextField()


    def __str__(self):
        return f"{self.name} {self.email}"

apps/gallery/models.py
from django.db import models

# Create your models here.



class Photo(models.Model):
    title = models.CharField(max_length=1023, blank=True)
    description = models.TextField(blank=True)
    photo = models.ImageField(upload_to='gallery/')
    views = models.IntegerField(default=1)
    added_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-added_date']


    def __str__(self):
        return self.title[:50]


class Video(models.Model):
    title = models.CharField(max_length=1023)
    link = models.URLField(max_length=200, blank=True)
    views = models.IntegerField(default=1)
    added_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-added_date']


    def __str__(self):
        return self.title[:50]

apps/library/models.py
from django.db import models
from apps.base.models import Department
# Create your models here.



class Library(models.Model):
    JOB_TITLE = (
        (1, 'Talaba'),
        (2, 'Professor'),
    )

    DOCUMENT_TYPE = (
        (1, 'Avtoreferat'),
        (2, 'Maqola'),
        (3, "Konferensiya to'plamlari"),
        (4, "Talabalar to'plamlari"),
        (5, "Monografiya"),
    )

    type = models.IntegerField(choices=DOCUMENT_TYPE)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True)

    full_name = models.CharField(max_length=255)
    job_title = models.IntegerField(choices=JOB_TITLE)

    title = models.CharField(max_length=1023)
    description = models.TextField()
    pdf = models.FileField(upload_to='documents/')

    views = models.IntegerField(default=1)
    added_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-added_date']


    def __str__(self):
        return self.title[:50]

apps/news/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.html import strip_tags

# Create your models here.


NEWS_TYPE = (
    (1, "Stipendiya e’lonlari"),
    (2, "Oliy ta’limdan keyingi ta’lim qabuli"),
    (3, "Malakaviy imtihon"),
    (4, "Himoya e’lonlari"),
    (5, "Doktorantlarni ilmiy seminar e’lonlari"),
    (6, "Konferensiya e’lonlari")
)


class News(models.Model):
    news_type = models.IntegerField(choices=NEWS_TYPE)
    title = models.CharField(max_length=1023)
    description = RichTextField()
    photo = models.ImageField(upload_to='news/', default='back1.jpg')
    min_desc = models.TextField(max_length=200, blank=True)  # yangi o'zgaruvchi
    views = models.IntegerField(default=1)
    added_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-added_date']


    def save(self, *args, **kwargs):
        # HTML teglarini olib tashlash
        plain_text = strip_tags(self.description)
        # Matnni 200 ta belgi bilan cheklash
        max_length = 100
        if len(plain_text) > max_length:
            self.min_desc = plain_text[:max_length]
        else:
            self.min_desc = plain_text
        super(News, self).save(*args, **kwargs)

    def __str__(self):
        return self.title[:50]

apps/base/forms.py
from django.forms import ModelForm


from .models import ContactUs

class ContactUsForm(ModelForm):
    class Meta:
        model = ContactUs
        fields = "__all__"

apps/base/views.py
from django.shortcuts import render, redirect
from django.db.models import Sum
from django.views.generic import View, ListView
from django.contrib import messages

from apps.library.models import Library
from apps.news.models import News
from apps.gallery.models import Photo, Video
from .forms import ContactUsForm

from .config import CURRENT_MONTH, CURRENT_YEAR
# Create your views here.


def home_page(request):

    last_three_library = Library.objects.all()[:3]
    last_three_news = News.objects.all()[:3]

    total_count_library = Library.objects.all().count()
    total_count_views = Library.objects.aggregate(Sum('views'))['views__sum']

    current_month_upload_views = Library.objects.filter(added_date__month=CURRENT_MONTH, added_date__year=CURRENT_YEAR).aggregate(Sum('views'))['views__sum']
    current_month_upload_count = Library.objects.filter(added_date__month=CURRENT_MONTH, added_date__year=CURRENT_YEAR).count()

    last_five_photo = Photo.objects.all()[:5]
    last_three_video = Video.objects.all()[:3]

    context = {
        "last_three_library": last_three_library,
        "last_three_news": last_three_news,
        "total_count_library": total_count_library,
        "total_count_views": total_count_views,
        "current_month_upload_views": current_month_upload_views,
        "current_month_upload_count": current_month_upload_count,
        "last_five_photo": last_five_photo,
        "last_three_video": last_three_video
    }


    return render(request, "home.html", context=context)


def faoliyat(request):
    return render(request, "faoliyat-details.html")


def contactus(request):

    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        print(form.data)
        if form.is_valid():
            form.save()
            messages.success(request, "Xabar jo'natildi.")
            return redirect('contactus')
        else:
            return render(request, 'blog/post_form.html', {'form': form})


    return render(request, "contact.html")

apps/gallery/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Photo, Video

# Create your views here.



class PhotoListView(ListView):
    model = Photo
    context_object_name = "photos"
    template_name = "gallery/list_photo.html"


class PhotoDetailView(DetailView):
    model = Photo
    context_object_name = "photo"
    template_name = "gallery/detail_photo.html"



class VideoListView(ListView):
    model = Video
    context_object_name = "videos"
    template_name = "gallery/list_video.html"


class VideoDetailView(DetailView):
    model = Video
    context_object_name = "video"
    template_name = "gallery/detail_photo.html"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Meta Tags -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="keywords" content="Site keywords here">
		<meta name="description" content="">
		<meta name='copyright' content=''>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		
		<!-- Title -->
        <title>Ilmiy bo'lim sayti</title>		
		<!-- Favicon -->
        <link rel="icon" href="{% static 'img/logo.webp' %}">
		
		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<!-- Nice Select CSS -->
		<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
		<!-- Font Awesome CSS -->
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
		<!-- icofont CSS -->
        <link rel="stylesheet" href="{% static 'css/icofont.css' %}">
		<!-- Slicknav -->
		<link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}">
		<!-- Owl Carousel CSS -->
        <link rel="stylesheet" href="{% static 'css/owl-carousel.css' %}">
		<!-- Datepicker CSS -->
		<link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
		<!-- Animate CSS -->
        <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
		<!-- Magnific Popup CSS -->
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
		
		<!-- Medipro CSS -->
        <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
		
    </head>
    <body>	
		<!-- Header Area -->
		<header class="header" >
			<!-- Header Inner -->
			<div class="header-inner">
				<div class="container">
					<div class="inner">
						<div class="row">
							<div class="col-lg-20 col-md-1 col-100">
								<!-- Start Logo -->
								<div class="logo">
									<a href="{% url 'home_page' %}"><img style="height: 50px; width: 50px;" src="{% static 'img/logo.webp' %}" alt="#"></a>
								</div>
								<!-- End Logo -->
								<!-- Mobile Nav -->
								<div class="mobile-nav"></div>
								<!-- End Mobile Nav -->
							</div>
							<div class="col-lg-20 col-md-9 col-20">
								<!-- Main Menu -->
								<div class="main-menu">
									<nav class="navigation">
										<ul class="nav menu">
											<li><a href="{% url 'library_list' %}">KUTUBXONA <i class="icofont-rounded-down"></i></a>
												<ul class="dropdown">
													{% for id, library in libraries %}
													<li><a href="{% url 'library_topic' id %}">{{ library }}</a></li>
													{% endfor %}
												</ul>	
											</li>
											<li><a href="{% url 'faoliyat' %}">Faoliyat </a></li>
											<li><a href="{% url 'news_list' %}">E'lonlar <i class="icofont-rounded-down"></i></a>
												<ul class="dropdown">
													{% for id, new in news %}
													<li><a href="{% url 'news_topic' id %}">{{ new }}</a></li>
													{% endfor %}
												</ul>
											</li>
											<li><a href="#">Mediateka <i class="icofont-rounded-down"></i></a>
												<ul class="dropdown">
													<li><a href="{% url 'photo_list' %}">FOTOGALEREYA</a></li>
													<li><a href="{% url 'video_list' %}">VIDEOGALEREYA</a></li>
												</ul>
											</li>
											<li><a href="{% url 'contactus' %}">Biz bilan bog'laning</a></li>
										</ul>
									</nav>
								</div>
								<!--/ End Main Menu -->
							</div>
							
						</div>
					</div>
				</div>
			</div>
			<!--/ End Header Inner -->
		</header>
		{% for message in messages %}
		<div class="container-fluid p-0">
			<div class="alert {{ message.tags }} alert-dismissible" role="alert" >
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="True">&times;</span>
			</button>
			{{ message }}
			</div>
		</div>
		{% endfor %}

		{% block context %}

		{% endblock %}
		
		<!-- Footer Area -->
		<footer id="footer" class="footer ">
			<!-- Footer Top -->
			<div class="footer-top">
				<div class="container">
					<div class="row">
						<div class="col-lg-3 col-md-6 col-12">
							<div class="single-footer">
								<h2>Biz haqimizda!</h2>
								<p>O'zbekiston Xalqaro Islom Akademiyasi Ilmiy-tadqiqotlar, innovatsiyalar va ilmiy-pedagogik kadrlar tayyorlash bo‘limi</p>
								<!-- Social -->
								<ul class="social">
									<li><a href="#"><i class="icofont-facebook"></i></a></li>
									<li><a href="#"><i class="icofont-youtube"></i></a></li>
									<li><a href="#"><i class="icofont-telegram"></i></a></li>
								</ul>
								<!-- End Social -->
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-12">
							<div class="single-footer f-link">
								<h2>Tezkor linklar</h2>
								<div class="row">
									<div class="col-lg-12 col-md-6 col-12">
										<ul>
											<li><a href="/library/library-list"><i class="fa fa-caret-right" aria-hidden="true"></i>Kutubxona</a></li>
											<li><a href="/faoliyat"><i class="fa fa-caret-right" aria-hidden="true"></i>Faoliyat</a></li>
											<li><a href="/news/news-list"><i class="fa fa-caret-right" aria-hidden="true"></i>E'lonlar</a></li>
											<li><a href="/gallery/photo-list"><i class="fa fa-caret-right" aria-hidden="true"></i>Fotogalereya</a></li>
											<li><a href="/gallery/video-list"><i class="fa fa-caret-right" aria-hidden="true"></i>Videogalereya</a></li>
											<li><a href="/contactus"><i class="fa fa-caret-right" aria-hidden="true"></i>Biz bilan bog'laning</a></li>
										</ul>
									</div>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-12">
							<div class="single-footer">
								<h2>Ish vaqti</h2>
								<ul class="time-sidual">
									<li class="day">Dushanba - Juma <span>8.30-17.00</span></li>
									<li class="day">Shanba <span>8.30-16.00</span></li>
								</ul>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-12">
							<div class="single-footer">
								<h2>Joylashuv</h2>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--/ End Footer Top -->
			<!-- Copyright -->
			<div class="copyright">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-12">
							<div class="copyright-content">
								<p>© Copyright 2024  |  All Rights Reserved by Ravskhan</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--/ End Copyright -->
		</footer>
		<!--/ End Footer Area -->
		
		<!-- jquery Min JS -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
		<!-- jquery Migrate JS -->
		<script src="{% static 'js/jquery-migrate-3.0.0.js' %}"></script>
		<!-- jquery Ui JS -->
		<script src="{% static 'js/jquery-ui.min.js' %}"></script>
		<!-- Easing JS -->
        <script src="{% static 'js/easing.js' %}"></script>
		<!-- Color JS -->
		<script src="{% static 'js/colors.js' %}"></script>
		<!-- Popper JS -->
		<script src="{% static 'js/popper.min.js' %}"></script>
		<!-- Bootstrap Datepicker JS -->
		<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
		<!-- Jquery Nav JS -->
        <script src="{% static 'js/jquery.nav.js' %}"></script>
		<!-- Slicknav JS -->
		<script src="{% static 'js/slicknav.min.js' %}"></script>
		<!-- ScrollUp JS -->
        <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
		<!-- Niceselect JS -->
		<script src="{% static 'js/niceselect.js' %}"></script>
		<!-- Tilt Jquery JS -->
		<script src="{% static 'js/tilt.jquery.min.js' %}"></script>
		<!-- Owl Carousel JS -->
        <script src="{% static 'js/owl-carousel.js' %}"></script>
		<!-- counterup JS -->
		<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
		<!-- Steller JS -->
		<script src="{% static 'js/steller.js' %}"></script>
		<!-- Wow JS -->
		<script src="{% static 'js/wow.min.js' %}"></script>
		<!-- Magnific Popup JS -->
		<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
		<!-- Counter Up CDN JS -->
		<script src="http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js'"></script>
		<!-- Bootstrap JS -->
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<!-- Main JS -->
		<script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block context %}				
		<!-- Start Contact Us -->
		<section class="contact-us section" style="padding-top: 30px;">
			<div class="container">
				<div class="inner">
					<div class="row"> 
						<div class="col-lg-6">
							<div class="contact-us-left" >
								<!--Start Google-map -->
								<div id="myMap">
									<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1256.7376063876777!2d69.25722966136382!3d41.323478431426814!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38ae8b6b41613dad%3A0xa0d408f674d9b96d!2z0JzQtdC20LTRg9C90LDRgNC-0LTQvdCw0Y8g0LjRgdC70LDQvNGB0LrQsNGPINCw0LrQsNC00LXQvNC40Y8g0KPQt9Cx0LXQutC40YHRgtCw0L3QsA!5e0!3m2!1sru!2s!4v1718537165890!5m2!1sru!2s" width="800" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
								</div>
								<!--/End Google-map -->
							</div>
						</div>
						<div class="col-lg-6">
							<div class="contact-us-form">
								<h2>Biz bilan bog'laning</h2>
								<p>Agar sizda qandaydir savol bo'lsa bizga yuboring!</p>
								<!-- Form -->
								<form class="form" method="post" action="">
									{% csrf_token %}
									<div class="row">
										<div class="col-lg-6">
											<div class="form-group">
												<input type="text" name="name" placeholder="Ism" required="">
											</div>
										</div>
										<div class="col-lg-6">
											<div class="form-group">
												<input type="email" name="email" placeholder="Email manzil" required="">
											</div>
										</div>
										<div class="col-lg-6">
											<div class="form-group">
												<input type="text" name="phone" placeholder="Telefon raqam" required="">
											</div>
										</div>
										<div class="col-lg-12">
											<div class="form-group">
												<textarea name="description" placeholder="Xabar matni" required=""></textarea>
											</div>
										</div>
										<div class="col-12">
											<div class="form-group login-btn">
												<button class="btn" type="submit">Yuborish</button>
											</div>
										</div>
									</div>
								</form>
								<!--/ End Form -->
							</div>
						</div>
					</div>
				</div>
				<div class="contact-info">
					<div class="row">
						<!-- single-info -->
						<div class="col-lg-4 col-12 ">
							<div class="single-info">
								<i class="icofont icofont-ui-call"></i>
								<div class="content">
									<h3>(+99871) 24- 00-56 </h3>
									<p>info@company.com</p>
								</div>
							</div>
						</div>
						<!--/End single-info -->
						<!-- single-info -->
						<div class="col-lg-4 col-12 ">
							<div class="single-info">
								<i class="icofont-google-map"></i>
								<div class="content">
									<h3>Manzil: </h3>
									<p>Toshkent shahar, A.Qodiriy 11-uy</p>
								</div>
							</div>
						</div>
						<!--/End single-info -->
						<!-- single-info -->
						<div class="col-lg-4 col-12 ">
							<div class="single-info">
								<i class="icofont icofont-wall-clock"></i>
								<div class="content">
									<h3>Dushanba - Shanba:<br>09:00 - 17:00</h3>
									<p>Yakshanba dam olish kuni</p>
								</div>
							</div>
						</div>
						<!--/End single-info -->
					</div>
				</div>
			</div>
		</section>
		<!--/ End Contact Us -->
		<script>
			let map;
			async function initMap() {
  			const { Map } = await google.maps.importLibrary("maps");
			map = new Map(document.getElementById("map"), {
    		center: { lat: -34.397, lng: 150.644 },
    		zoom: 8,
		});
			}
		initMap();
		</script>
{% endblock %}		

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block context %}
<section class="slider" style="background-image: url( {% static 'img/black1.png' %} );">
    <div class="hero-slider">
        <!-- Start Single Slider -->
        {% for library in last_three_library %}
        <div class="single-slider">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7">
                        <div class="text">
                            <h1 class="truncate">{{ library.title }}</h1>
                            <p class="truncate">{{ library.description }}</p>
                            <div class="button">
                                <a href="{% url 'library_deatil' library.id %}" class="btn">Kirish</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>  
        </div>        
        {% endfor %}
        <!-- End Single Slider -->
    </div>
</section>
<!--/ End Slider Area -->


<!-- Start Schedule Area -->
<section class="schedule">
    <div class="container">
        <div class="schedule-inner">
            <div class="row">
                {% for news in last_three_news %}    
                <div class="col-lg-4 col-md-6 col-12 ">
                    <!-- single-schedule -->
                    <div class="single-schedule first">
                        <div class="inner">
                            <div class="icon">
                                <i class="fa fa-book"></i>
                            </div>
                            <div class="single-content">
                                <span>{{ news.get_news_type_display }}</span>
                                <h4>{{ news.title }}</h4>
                                <p>{{ news.min_desc | safe }}</p>
                                <a href="{% url 'news-detail' news.id %}">Kirish<i class="fa fa-long-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
<!--/End Start schedule Area -->

<!-- Start Feautes -->
<section class="Feautes section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>O'zbekiston xalqaro islom akademiyasi</h2>
                    <p>Ilmiy-tadqiqotlar, innovatsiyalar va ilmiy-pedagogik kadrlar tayyorlash bo‘limining vazifalari:</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-12">
                <!-- Start Single features -->
                <div class="single-features">
                    <div class="signle-icon">
                        <i class="icofont-book"></i>
                    </div>
                    <h3>1</h3>
                    <p>Akademiyaning ilmiy tadqiqot ishlari rejasini ishlab chiqish va amalga oshirilishini muntazam nazorat qilish</p>
                </div>
                <!-- End Single features -->
            </div>
            <div class="col-lg-4 col-12">
                <!-- Start Single features -->
                <div class="single-features">
                    <div class="signle-icon">
                        <i class="icofont-student-alt"></i>
                    </div>
                    <h3>2</h3>
                    <p>Akademiyada tayanch doktorantura, doktorantura hamda mustaqil izlanuvchilar qabul jarayonini tashkil etish</p>
                </div>
                <!-- End Single features -->
            </div>
            <div class="col-lg-4 col-12">
                <!-- Start Single features -->
                <div class="single-features last">
                    <div class="signle-icon">
                        <i class="icofont-university"></i>
                    </div>
                    <h3>3</h3>
                    <p>Akademiyada tayanch doktorantura, doktorantura hamda mustaqil izlanuvchilar qabul jarayonini tashkil etish</p>
                </div>
                <!-- End Single features -->
            </div>
        </div>
    </div>
</section>
<!--/ End Feautes -->

<!-- Start Fun-facts -->
<div id="fun-facts" class="fun-facts section overlay">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-12">
                <!-- Start Single Fun -->
                <div class="single-fun">
                    <i class="icofont-book"></i>
                    <div class="content">
                        <span class="counter">{{ total_count_library }}</span>
                        <p>Jami yuklangan materiallar</p>
                    </div>
                </div>
                <!-- End Single Fun -->
            </div>
            <div class="col-lg-3 col-md-6 col-12">
                <!-- Start Single Fun -->
                <div class="single-fun">
                    <i class="icofont-eye"></i>
                    <div class="content">
                        <span class="counter">{{ total_count_views }}</span>
                        <p>Jami ko'rishlar soni</p>
                    </div>
                </div>
                <!-- End Single Fun -->
            </div>
            <div class="col-lg-3 col-md-6 col-12">
                <!-- Start Single Fun -->
                <div class="single-fun">
                    <i class="icofont-book"></i>
                    <div class="content">
                        <span class="counter">{{ current_month_upload_count }}</span>
                        <p>Bu oyda yuklangan materiallar soni</p>
                    </div>
                </div>
                <!-- End Single Fun -->
            </div>
            <div class="col-lg-3 col-md-6 col-12">
                <!-- Start Single Fun -->
                <div class="single-fun">
                    <i class="icofont-eye"></i>
                    <div class="content">
                        <span class="counter">{{ current_month_upload_views }}</span>
                        <p>Bu oydagi ko'rishlar soni</p>
                    </div>
                </div>
                <!-- End Single Fun -->
            </div>
        </div>
    </div>
</div>
<!--/ End Fun-facts -->



<!-- Start portfolio -->
<section class="portfolio section" >
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>FOTOGALEREYA</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-12">
                <div class="owl-carousel portfolio-slider">
                    {% for img in last_five_photo %}
                    <div class="single-pf">
                        <img src="{{ img.photo.url }}" alt="#">
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
<!--/ End portfolio -->


{% endblock %}

templates/paginatoin.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?page={{ page_obj.previous_page_number }}" class="page-link"><< Orqaga</a>
        </li>
      {% endif %}
      
      <li class="page-item">
        <a href="#" class="page-link">
          Sahifa {{ page_obj.number }} // {{ page_obj.paginator.num_pages }}.
        </a>
      </li>
      <li class="page-item">
        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}" class="page-link">Oldinga >></a>
        {% endif %}
      </li>
    </ul>
  </nav>