apps/library/urls.py
from django.urls import path

from .views import LibraryListView, LibraryDetailView, library_topic_view


urlpatterns = [
    path("library-list/", LibraryListView.as_view(), name="library_list"),
    path("library_topic/<int:pk>", library_topic_view, name="library_topic"),
    path("library-detail/<int:pk>", LibraryDetailView.as_view(), name="library_deatil")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [ 
    path('admin/', admin.site.urls),
    path("", include("apps.base.urls")),
    path("gallery/", include("apps.gallery.urls")),
    path("library/", include("apps.library.urls")),
    path("news/", include("apps.news.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/library/models.py
from django.db import models
from apps.base.models import Department
# Create your models here.



class Library(models.Model):
    JOB_TITLE = (
        (1, 'Talaba'),
        (2, 'Professor'),
    )

    DOCUMENT_TYPE = (
        (1, 'Avtoreferat'),
        (2, 'Maqola'),
        (3, "Konferensiya to'plamlari"),
        (4, "Talabalar to'plamlari"),
        (5, "Monografiya"),
    )

    type = models.IntegerField(choices=DOCUMENT_TYPE)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True)

    full_name = models.CharField(max_length=255)
    job_title = models.IntegerField(choices=JOB_TITLE)

    title = models.CharField(max_length=1023)
    description = models.TextField()
    pdf = models.FileField(upload_to='documents/')

    views = models.IntegerField(default=1)
    added_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-added_date']


    def __str__(self):
        return self.title[:50]

apps/library/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Library

# Create your views here.


class LibraryListView(ListView):
    model = Library
    context_object_name = "libraries_objects"
    template_name = "library/list_library.html"
    paginate_by = 15


    def get_queryset(self):
        query = self.request.GET.get('q')

        if query:
            return Library.objects.filter(title__icontains=query)

        return Library.objects.all()


def library_topic_view(request, pk):
    libraries = Library.objects.filter(type=pk)
    return render(request, "library/list_library.html", {"libraries_objects": libraries})


class LibraryDetailView(DetailView):
    model = Library
    context_object_name = "lib"
    template_name = "library/detail_library.html"
    
    def get_context_data(self, **kwargs):
        
        library = self.get_object()
        library.views += 1
        library.save()

        return super().get_context_data(**kwargs)

templates/library/detail_library.html
{% extends 'base.html' %}

{% block context %}	
		<!-- Start Portfolio Details Area -->
		<section class="pf-details section">
			<div class="container">
				<div class="row">
					<div class="col-12">
						<div class="inner-content">
							<div class="date">
								<ul>
									<li><span>Hujjat turi :</span> {{ lib.get_type_display }} </li>
                                    <li><span>Qo'shilgan sana :</span> {{ lib.added_date }} </li>
									<li><span>Ko'rishlar soni :</span>{{ lib.views }}</li>
								</ul>
							</div>
                            <div class="date">
                                <ul>
                                    <li><span>Kafedra :</span> {{ lib.department.name }} </li>
                                    <li><span>Talaba/Professor</span>{{ lib.get_job_title_display }}</li>
                                    <li><span>Ism sharifi :</span>{{ lib.full_name }}</li>
                                </ul>    
                            </div>
							<div class="body-text">
								<h3>{{ lib.title }}</h3>
                                <p>{{ lib.description }}</p>

                                <div class="mt-2">
                                    <a href="{{ lib.pdf.url }}" target="_blank" class="btn btn-primary btn-block text-white">Ko'rish</a>
                                </div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End Portfolio Details Area -->


{% endblock %}

templates/library/list_library.html
{% extends 'base.html' %}

{% block context %}

<div class="container mb-5">
    <div class="row">
        <div class="col-lg-8 col-12">
            <div class="single-widget recent-post">
                <!-- Single Post -->
                 <br><br>
                {% for lb in libraries_objects %}
                    <div class="single-post">
                        <div class="content">
                            <h5><a href="{% url 'library_deatil' lb.id %}">{{ lb.title  }}</a></h5>
                            <ul class="comment">
                                <li><i class="fa fa-calendar" aria-hidden="true"></i>&nbsp;&nbsp;{{ lb.added_date }}&nbsp;&nbsp;&nbsp;<i class="fa fa-eye" aria-hidden="true"></i>&nbsp;&nbsp;{{ lb.views }}</li>
                            </ul>
                            <br>
                        </div>
                    </div>
                {% endfor %}
                <!-- End Single Post -->
            </div>
            
            {% include 'paginatoin.html' %}
        </div>
        
        
        <div class="col-lg-4 col-12">
            <div class="main-sidebar">
                <!-- Single Widget -->
                <form method="get">
                    <div class="single-widget search">
                        <div class="form">
                            <input type="text" name="q" value="{{ request.GET.q }}">
                            <button class="button" type="submit"><i class="fa fa-search"></i></button>
                        </div>
                    </div>    
                </form>
                <!--/ End Single Widget -->
                <br><br>
                <!-- Single Widget -->
                <div class="single-widget category">
                    <h3 class="title">KUTUBXONA</h3>
                    <ul class="categor-list">
                        {% for id, library in libraries %}
                            <li><a href="{% url 'library_topic' id %}">{{ library }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!--/ End Single Widget -->
            </div>
        </div>
    </div>
</div>


{% endblock %}